// =============================================================
// GENERATED by /opt/data/cache/mhr_desc_generate.py (S3) — 勿手改
// Source: official API 2026-08-27 (267 cards). Only SAFE full-parse
// cards are emitted (人工過目 2026-08-27). Remaining ~216 cards:
// manual (EFFECTS_DESCRIPTOR.md S4 TODO).
// =============================================================
window.MHR_EFFECTS_DATA = {
 "BP01-001": [
  {
   "trig": "TRIG",
   "slot": "FIELD",
   "vars": {
    "X": "retreated_by_this_call"
   },
   "cond": [
    {
     "if": "by_calling"
    }
   ],
   "ops": [
    {
     "op": "prune",
     "target": "opp_field",
     "filter": {
      "lv": {
       "op": "<=",
       "var": "X"
      }
     }
    }
   ]
  }
 ],
 "BP01-004": [
  {
   "trig": "AUTO",
   "slot": "FIELD",
   "vars": {
    "X": "count_opp_battle"
   },
   "cond": [
    {
     "if": "all_my_field_attr",
     "attr": "Red"
    }
   ],
   "ops": [
    {
     "op": "power_mod",
     "target": "self",
     "amount": {
      "var": "X",
      "scale": 1000
     },
     "duration": "permanent"
    },
    {
     "op": "lv_mod",
     "target": "self",
     "amount": {
      "var": "X",
      "scale": 1
     }
    }
   ]
  }
 ],
 "BP01-006": [
  {
   "trig": "AUTO",
   "slot": "FIELD",
   "cond": [
    {
     "if": "my_hand_odd"
    }
   ],
   "ops": [
    {
     "op": "r_mod",
     "target": "self",
     "amount": 2,
     "duration": "permanent"
    }
   ]
  },
  {
   "trig": "AUTO",
   "slot": "FIELD",
   "cond": [
    {
     "if": "my_hand_even"
    }
   ],
   "ops": [
    {
     "op": "power_mod",
     "target": "self",
     "amount": 5500,
     "duration": "permanent"
    }
   ]
  }
 ],
 "BP01-011": [
  {
   "trig": "TRIG",
   "slot": "FIELD",
   "cond": [
    {
     "if": "by_calling"
    }
   ],
   "ops": [
    {
     "op": "draw",
     "n": 1
    },
    {
     "op": "attack_bonus",
     "target": "self",
     "duration": "this_turn"
    }
   ]
  }
 ],
 "BP01-056": [
  {
   "trig": "AUTO",
   "slot": "BATTLE",
   "cond": [
    {
     "if": "opp_front_r_is",
     "n": 1
    }
   ],
   "ops": [
    {
     "op": "power_mod",
     "target": "self",
     "amount": 1500,
     "duration": "permanent"
    }
   ]
  }
 ],
 "BP01-058": [
  {
   "trig": "AUTO",
   "slot": "FIELD",
   "cond": [
    {
     "if": "opp_battle_total_r_ge",
     "n": 3
    }
   ],
   "ops": [
    {
     "op": "power_mod",
     "target": "self",
     "amount": 3500,
     "duration": "permanent"
    }
   ]
  }
 ],
 "BP01-060": [
  {
   "trig": "TRIG",
   "slot": "FIELD",
   "cond": [
    {
     "if": "by_calling"
    }
   ],
   "ops": [
    {
     "op": "power_mod",
     "target": "opp_front",
     "amount": -1000,
     "duration": "this_turn"
    }
   ]
  }
 ],
 "BP01-064": [
  {
   "trig": "AUTO",
   "slot": "BATTLE",
   "cond": [
    {
     "if": "my_battle_has_attr_except_self",
     "attr": "Blue"
    }
   ],
   "ops": [
    {
     "op": "power_mod",
     "target": "self",
     "amount": 2500,
     "duration": "permanent"
    }
   ]
  }
 ],
 "BP01-071": [
  {
   "trig": "AUTO",
   "slot": "FRONT",
   "ops": [
    {
     "op": "power_mod",
     "target": "self",
     "amount": 1000,
     "duration": "permanent"
    }
   ]
  },
  {
   "trig": "AUTO",
   "slot": "WING",
   "ops": [
    {
     "op": "r_mod",
     "target": "self",
     "amount": 2,
     "duration": "permanent"
    }
   ]
  }
 ],
 "BP01-088": [
  {
   "trig": "AUTO",
   "slot": "BATTLE",
   "cond": [
    {
     "if": "opp_battle_has_power_ge",
     "n": 5000
    }
   ],
   "ops": [
    {
     "op": "r_mod",
     "target": "self",
     "amount": 3,
     "duration": "permanent"
    }
   ]
  }
 ],
 "SD01-008": [
  {
   "trig": "AUTO",
   "slot": "HAND",
   "cond": [
    {
     "if": "both_field_no_lv4",
     "n": 4
    }
   ],
   "ops": [
    {
     "op": "lv_mod",
     "target": "self",
     "amount": -2
    }
   ]
  }
 ],
 "SD02-005": [
  {
   "trig": "ACTI",
   "slot": "BASE",
   "once": true,
   "ops": [
    {
     "op": "draw",
     "n": 1
    },
    {
     "op": "discard",
     "n": 3,
     "target": "my_deck_top"
    },
    {
     "op": "cover_self"
    }
   ]
  }
 ],
 "SD02-017": [
  {
   "trig": "TRIG",
   "slot": "FIELD",
   "cond": [
    {
     "if": "by_calling"
    }
   ],
   "ops": [
    {
     "op": "power_mod",
     "target": "opp_front",
     "amount": -1000,
     "duration": "this_turn"
    }
   ]
  }
 ],
 "SD02-018": [
  {
   "trig": "AUTO",
   "slot": "BATTLE",
   "cond": [
    {
     "if": "opp_front_r_is",
     "n": 1
    }
   ],
   "ops": [
    {
     "op": "power_mod",
     "target": "self",
     "amount": 1500,
     "duration": "permanent"
    }
   ]
  }
 ],
 "SD03-004": [
  {
   "trig": "AUTO",
   "slot": "BACK",
   "ops": [
    {
     "op": "r_mod",
     "target": "self",
     "amount": 2,
     "duration": "permanent"
    }
   ]
  },
  {
   "trig": "AUTO",
   "slot": "BASE",
   "ops": [
    {
     "op": "lv_mod",
     "target": "self",
     "amount": 1
    }
   ]
  }
 ]
};
