// =============================================================
// GENERATED by /opt/data/cache/mhr_desc_generate.py (S3) — 勿手改
// Source: official API 2026-08-27 (267 cards). Only SAFE full-parse
// cards are emitted (人工過目 2026-08-27). Remaining ~216 cards:
// manual (EFFECTS_DESCRIPTOR.md S4 TODO).
// =============================================================
window.MHR_EFFECTS_DATA = {
 "BP01-001": [
  {
   "trig": "TRIG",
   "slot": "FIELD",
   "vars": {
    "X": "retreated_by_this_call"
   },
   "cond": [
    {
     "if": "by_calling"
    }
   ],
   "ops": [
    {
     "op": "prune",
     "target": "opp_field",
     "filter": {
      "lv": {
       "op": "<=",
       "var": "X"
      }
     }
    }
   ]
  }
 ],
 "BP01-004": [
  {
   "trig": "AUTO",
   "slot": "FIELD",
   "vars": {
    "X": "count_opp_battle"
   },
   "cond": [
    {
     "if": "all_my_field_attr",
     "attr": "Red"
    }
   ],
   "ops": [
    {
     "op": "power_mod",
     "target": "self",
     "amount": {
      "var": "X",
      "scale": 1000
     },
     "duration": "permanent"
    },
    {
     "op": "lv_mod",
     "target": "self",
     "amount": {
      "var": "X",
      "scale": 1
     }
    }
   ]
  }
 ],
 "BP01-060": [
  {
   "trig": "TRIG",
   "slot": "FIELD",
   "cond": [
    {
     "if": "by_calling"
    }
   ],
   "ops": [
    {
     "op": "power_mod",
     "target": "opp_front",
     "amount": -1000,
     "duration": "this_turn"
    }
   ]
  }
 ],
 "BP01-071": [
  {
   "trig": "AUTO",
   "slot": "FRONT",
   "ops": [
    {
     "op": "power_mod",
     "target": "self",
     "amount": 1000,
     "duration": "permanent"
    }
   ]
  },
  {
   "trig": "AUTO",
   "slot": "WING",
   "ops": [
    {
     "op": "r_mod",
     "target": "self",
     "amount": 2,
     "duration": "permanent"
    }
   ]
  }
 ],
 "SD02-017": [
  {
   "trig": "TRIG",
   "slot": "FIELD",
   "cond": [
    {
     "if": "by_calling"
    }
   ],
   "ops": [
    {
     "op": "power_mod",
     "target": "opp_front",
     "amount": -1000,
     "duration": "this_turn"
    }
   ]
  }
 ],
 "SD03-004": [
  {
   "trig": "AUTO",
   "slot": "BACK",
   "ops": [
    {
     "op": "r_mod",
     "target": "self",
     "amount": 2,
     "duration": "permanent"
    }
   ]
  },
  {
   "trig": "AUTO",
   "slot": "BASE",
   "ops": [
    {
     "op": "lv_mod",
     "target": "self",
     "amount": 1
    }
   ]
  }
 ]
};
