// =============================================================
// Marvel Hero Rush TCG — Engine v0.2
// Aligned to official 簡中 rulebook (doc_97084c6e..., 17 pages).
// Pure game logic. No DOM access. UI subscribes via callbacks.
// =============================================================
// State shape:
//   {
//     players: { P, A },
//     activeSide: "P" | "A",
//     turn: int,
//     phase: "DRAW" | "ACTION" | "BATTLE" | "RESPOND" | "END",
//     log: [{ side, msg }],
//     winner: null | "P" | "A" | "DRAW",
//     deckNames: { P, A },
//     firstPlayer: "P" | "A",
//     pending: null | { kind, ... },   // modal for UI to resolve
//     turnFlags: { [side]: {
//         setDeployUsed, callCount, movedUids, attackedUids
//         counterStepUsed, // for RESPOND/BATTLE counter step
//     }}
//   }
// playerState = {
//   name, deckLabel,
//   deck[], hand[], retreat[], void[], rushDeck[], timeline[],
//   battle: { front, back, wing: [w1, w2] },   // 戰區
//   base: { faceDown: [] },                    // 基地 (face-down set cards)
//   rushPoints,                                // = timeline.length
//   attached: { uid: [card,...] },
//   movedThisTurn: { uid: true },
//   attackedThisTurn: { uid: true },
// }
// Card instances are full objects; identity preserved across
// hand → field → retreat/void so effect source tracking works.
// =============================================================

(function (global) {
  "use strict";

  const DATA = global.MHR_DATA;
  const DECKS = DATA.DECKS;

  // ---- M1: declarative effect descriptors (DSL — see EFFECTS_DESCRIPTOR.md) ----
  // 對應每張 card_no 嘅 declarative descriptor。M2 (S3) 自動 parse 簡單卡後會擴展。
  // 注意：deckbuilder 嘅 cards.js 唔郁（MHR_DATA.CARDS source-of-truth），descriptor
  // 由本 map 透過 card_no 注入 → 確保 engine 自足，UI deckbuilder 不受影響。
  // S3: js/effects-data.js（generated by mhr_desc_generate.py）自動併入；BP01-011 係 M1 demo。
  const EFFECTS_DESCRIPTORS = Object.assign(
    {},
    (global.MHR_EFFECTS_DATA || {}),
    {
      "BP01-011": [
        { trig: "TRIG", slot: "FIELD",
          cond: [ { if: "by_calling" } ],
          ops: [
            { op: "draw", n: 1 },
            { op: "attack_bonus", target: "self", duration: "this_turn" },
          ] },
      ],
      // M4: BP01-002 COUNTER·ACTI【HAND】— DSL counter frame 實證（手寫，target=attacker）
      "BP01-002": [
        { trig: "COUNTER_ACTI", slot: "HAND",
          cost: [ { op: "discard_self_from_hand" } ],
          ops: [ { op: "power_mod", target: "attacker", amount: -2000, duration: "this_turn" } ] },
      ],
      // 其他卡 descriptors 由 S3（S3 JARVIS+Senku）批量 parse 後補入。
      // demo 範圍只放 BP01-011 Thor 確實行新 interpreter 路徑。
    }
  );

  function injectEffects(c) {
    const desc = EFFECTS_DESCRIPTORS[c.card_no];
    if (desc) c.effects = desc;
    return c;
  }

  // ---- Constants (official) ----
  const RUSH_TO_WIN = 9;          // 9 張衝擊卡 或 對方牌組 0
  const HAND_SIZE_START = 6;      // 起始手牌 6
  const HAND_SIZE_MAX = 9;        // 回合結束 >9 棄至 9
  const BASE_SIZE_MAX = 6;        // 基地上限 6 張（角色卡和蓋卡）
  const RUSH_DECK_SIZE = 9;       // 衝擊卡組 9 張
  const BATTLE_SIZE = 4;          // 先鋒 + 後衛 + 2 側翼

  // ---- Real Rush Point token pool (synced from MHR_DATA 2026-08-15) ----
  // Each set (BP01, SD01..SD04) provides its own RP token art. A player's
  // rush deck is built from the same set as their main deck so the token
  // art matches the box art in their hand.
  const ALL_CARDS = (global.MHR_DATA && global.MHR_DATA.CARDS) || global.CARDS || [];
  const RUSH_POOL_BY_SET = {};
  ALL_CARDS.forEach(c => {
    if (c.type === "impact") {
      (RUSH_POOL_BY_SET[c.set] = RUSH_POOL_BY_SET[c.set] || []).push(c);
    }
  });

  // ---- Event bus ----
  const EVT = {
    LOG: "log",
    STATE: "state",
    PROMPT: "prompt",
    PHASE: "phase",
    TURN: "turn",
    WIN: "win",
    ATTACK: "attack",   // (attackerSide, attackerUid, targetUid, kind)
                        //  kind = "card" | "weakness:front"|"weakness:back"|"weakness:wing1"|"weakness:wing2"
  };

  // ---- helpers ----
  const uid = (() => {
    let n = 1;
    return () => "c" + (n++);
  })();

  function cloneCard(c) {
    return injectEffects(Object.assign({}, c, { _uid: uid() }));
  }

  function log(state, msg, side) {
    state.log.push({ side: side || null, msg });
  }

  // Fisher-Yates shuffle（共用；mulligan / newPlayer / buildRushDeck 一致）
  function fisherYates(arr) {
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr;
  }

  // 確保衝擊卡組 9 張：自選不足 9 時用 BP01 pool 補（M1.5 自選衝擊卡組）
  function padRushDeck(cards) {
    const out = cards.slice();
    if (out.length >= RUSH_DECK_SIZE) return fisherYates(out.slice(0, RUSH_DECK_SIZE));
    const bpPool = RUSH_POOL_BY_SET.BP01 || [];
    let bi = 0;
    while (out.length < RUSH_DECK_SIZE && bpPool.length > 0) {
      out.push(Object.assign({}, bpPool[bi % bpPool.length], { _uid: "rp" + Math.random().toString(36).slice(2, 8) }));
      bi++;
    }
    return fisherYates(out);
  }

  // =============================================================
  // 0. SETUP — per official page 9
  // =============================================================

  // Build a 9-card rush deck. Strategy: pool tokens from the main deck's
  // *dominant* set first (visually matches the box art in the player's
  // hand — the set they have the most cards from). If that pool is
  // smaller than 9 (e.g. SD01..SD04 only ship 1 token each), top up from
  // BP01 (which has 30 unique tokens). Final fallback to random uid if
  // no real RP cards available at all.
  function buildRushDeck(deckArr) {
    // Tally set distribution in the deck so the RP tokens match the
    // set the player has the most cards from (BP01 deck → BP01 tokens).
    const setTally = Object.create(null);
    deckArr.forEach(c => { if (c && c.set) setTally[c.set] = (setTally[c.set] || 0) + 1; });
    const dominantSet = Object.entries(setTally).sort((a, b) => b[1] - a[1])[0];
    const setName = (dominantSet && dominantSet[0]) || "BP01";

    const ownPool = RUSH_POOL_BY_SET[setName] || [];
    const bpPool = RUSH_POOL_BY_SET.BP01 || [];
    if (ownPool.length + bpPool.length === 0) {
      return Array.from({ length: RUSH_DECK_SIZE }, () => ({ _uid: "rp" + Math.random().toString(36).slice(2, 8) }));
    }
    // Shuffle each pool independently.
    const shuffle = arr => {
      const a = arr.slice();
      for (let i = a.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [a[i], a[j]] = [a[j], a[i]];
      }
      return a;
    };
    const ownShuffled = shuffle(ownPool);
    const bpShuffled = shuffle(bpPool);
    const out = [];
    // First, take own-pool tokens (with replacement if pool < ownShuffled).
    while (out.length < Math.min(RUSH_DECK_SIZE, ownShuffled.length)) {
      out.push(Object.assign({}, ownShuffled[out.length % ownShuffled.length], { _uid: "rp" + Math.random().toString(36).slice(2, 8) }));
    }
    // Top up from BP01 if we still need more.
    let bi = 0;
    while (out.length < RUSH_DECK_SIZE) {
      out.push(Object.assign({}, bpShuffled[bi % bpShuffled.length], { _uid: "rp" + Math.random().toString(36).slice(2, 8) }));
      bi++;
    }
    return out;
  }

  function newPlayer(name, deckArr, deckLabel, rushCards) {
    const deck = fisherYates(deckArr.map(cloneCard));
    return {
      name,
      deckLabel,
      deck,
      hand: [],
      retreat: [],
      voidZone: [],
      battle: { front: null, back: null, wing: [null, null] },
      base: { faceDown: [] },
      // 衝擊卡組 — 玩家自選 9 張實卡（M1.5）；否則自動（dominant set 實卡）
      rushDeck: rushCards && rushCards.length ? padRushDeck(rushCards) : buildRushDeck(deck),
      // 時間線 (placed rush cards, = 玩家勝利步伐)
      timeline: [],
      rushPoints: 0,        // 同步 = timeline.length
      attached: {},
      // per-turn flags live on state.turnFlags[side]
    };
  }

  function initGame(deckNameP, deckNameA, rushCardsP, rushCardsA) {
    const dp = DECKS[deckNameP];
    const da = DECKS[deckNameA];
    if (!dp || !da) throw new Error("Unknown deck: " + (deckNameP || deckNameA));

    const state = {
      players: {
        P: newPlayer("Player", dp, deckNameP, rushCardsP),
        A: newPlayer("AI", da, deckNameA, rushCardsA),
      },
      activeSide: "P",
      turn: 1,
      phase: "DRAW",
      log: [],
      winner: null,
      deckNames: { P: deckNameP, A: deckNameA },
      firstPlayer: "P",
      pending: null,
      turnFlags: {},
    };

    // 雙方抽 6 張起始手牌
    drawTo(state, "P", HAND_SIZE_START);
    drawTo(state, "A", HAND_SIZE_START);

    log(state, `=== 遊戲開始 ===  ${deckNameP} vs ${deckNameA}`);
    log(state, `第 1 回合（先攻：Player）`);

    initTurnFlags(state, "P");

    // M1.5: Mulligan（官方 P9）— 雙方抽 6 後進入調整起始手牌階段
    // 先攻玩家先決定：蓋放回卡組底 → 抽等量 → 洗牌；後攻再決定。
    state.phase = "MULLIGAN";
    state.mulliganDone = { P: false, A: false };
    log(state, "調整起始手牌（Mulligan）：先攻 Player 先決定，AI 後決定");
    return state;
  }

  function initTurnFlags(state, side) {
    state.turnFlags[side] = {
      setDeployUsed: false,   // 基地部署 1 次/回合
      callCount: 0,           // 行動號召 上限 3 次（先攻首回合 1）
      movedUids: {},          // 戰基移動 每角色 1 次
      attackedUids: {},       // 戰鬥 每角色 1 次
      counterStepUsed: false, // 應對步驟 1 次/回合
      doubleAttackUids: {},   // BP01-011 雙攻旗
      oncePerTurnUids: {},    // ONCE PER TURN 已觸發 uid
    };
  }

  // Max call count for current turn (先攻首回合 1 次, 否則 3 次)
  function maxCallCount(state, side) {
    if (state.turn === 1 && state.firstPlayer === side) return 1;
    return 3;
  }

  // First-turn battle phase is skipped for the first player.
  function isFirstTurnBattleSkipped(state, side) {
    return state.turn === 1 && state.firstPlayer === side;
  }

  // =============================================================
  // 1. DRAW / DISCARD helpers
  // =============================================================
  function drawTo(state, side, n) {
    const p = state.players[side];
    while (p.hand.length < n) {
      if (p.deck.length === 0) {
        // Deck-out: opponent wins
        const opp = side === "P" ? "A" : "P";
        if (!state.winner) {
          log(state, `${p.name} 牌組耗盡！${state.players[opp].name} 獲勝（deck-out）`, opp);
          state.winner = opp;
        }
        return;
      }
      p.hand.push(p.deck.shift());
    }
  }

  function drawN(state, side, n) {
    const p = state.players[side];
    for (let i = 0; i < n; i++) {
      if (p.deck.length === 0) {
        const opp = side === "P" ? "A" : "P";
        if (!state.winner) {
          log(state, `${p.name} 牌組耗盡！${state.players[opp].name} 獲勝（deck-out）`, opp);
          state.winner = opp;
        }
        return;
      }
      p.hand.push(p.deck.shift());
    }
  }

  function discardDownTo(state, side, max) {
    const p = state.players[side];
    while (p.hand.length > max) {
      // For simplicity discard the LAST card in hand to RETREAT (= 捨棄 → 撤退)
      const c = p.hand.pop();
      p.retreat.push(c);
      log(state, `${p.name} 捨棄 ${shortName(c)} → RETREAT`, side);
    }
  }

  // =============================================================
  // 1.5 MULLIGAN — 官方 P9（調整起始手牌）
  // 先攻玩家先決定：把要調整嘅手牌蓋放回卡組底 → 從卡組頂抽等量 → 洗混卡組。
  // 後攻再決定。階段 MULLIGAN 只喺遊戲開始出現一次。
  // =============================================================
  function mulligan(state, side, handIndices) {
    const p = state.players[side];
    if (state.phase !== "MULLIGAN") return { ok: false, err: "唔係調整起始手牌階段" };
    if (state.mulliganDone[side]) return { ok: false, err: "已調整過" };

    // 由高 index 開始移除，避免 index 移位；去重 + 過濾非法 index
    const idxs = [...new Set((handIndices || []).map(Number))]
      .filter(i => Number.isInteger(i) && i >= 0 && i < p.hand.length)
      .sort((a, b) => b - a);
    const returned = idxs.map(i => p.hand.splice(i, 1)[0]).reverse(); // 還原原手牌次序
    const n = returned.length;

    // 1. 蓋放回卡組底（deck 頂 = index 0，抽牌用 shift → 底 = push）
    for (const c of returned) p.deck.push(c);
    // 2. 從卡組頂抽等量
    for (let i = 0; i < n && p.deck.length > 0; i++) p.hand.push(p.deck.shift());
    // 3. 洗混卡組
    fisherYates(p.deck);

    state.mulliganDone[side] = true;
    log(state, `${p.name} 調整起始手牌：放回 ${n} 張 → 抽 ${n} → 洗牌`, side);
    return { ok: true, returned: n };
  }

  // =============================================================
  // 2. PHASE FLOW (official 6 步: 開始 → 抽2 → 行動 → 戰鬥 → 應對 → 結束)
  // =============================================================
  // startTurn: 開始 → 抽 2 → 進 行動
  function startTurn(state) {
    const side = state.activeSide;
    initTurnFlags(state, side);

    // 1. 回合開始 — 觸發回合開始效果
    // M1: 回合開始效果 (未實裝 TRIG【TURN_START】 系列, 但保留 hook)
    // S3: AUTO 常駐效果 refresh（phase_change event → AUTO descriptors 重算）
    if (global.MHR_EFFECTS && global.MHR_EFFECTS.runEffects) {
      global.MHR_EFFECTS.runEffects(state, side, { kind: "phase_change" });
    }

    // 2. 抽卡階段 — 抽 2 張
    drawN(state, side, 2);
    log(state, `${state.players[side].name} 抽 2 張（手牌 ${state.players[side].hand.length}）`, side);

    state.phase = "ACTION";
  }

  // endTurn: 結束 → 切邊
  function endTurn(state) {
    const side = state.activeSide;
    const p = state.players[side];

    // 6. 回合結束：①觸發回合結束效果 ②本回合效果結束（_powerMod 重置）③手牌 >9 棄至 9
    p.attached = p.attached || {};
    battleChars(p).forEach(({ card }) => { card._powerMod = 0; card._rMod = 0; });

    discardDownTo(state, side, HAND_SIZE_MAX);
    log(state, `${p.name} 回合結束（手牌上限 ${HAND_SIZE_MAX}）`, side);

    // Switch side
    state.activeSide = side === "P" ? "A" : "P";
    if (state.activeSide === "P") state.turn++;
    state.phase = "DRAW";
    state.pending = null;

    if (state.winner) {
      log(state, `遊戲結束！贏家：${state.players[state.winner].name}`);
      return;
    }
    log(state, `第 ${state.turn} 回合 — ${state.players[state.activeSide].name}`);
    startTurn(state);
  }

  // AI / opponent auto-resolves any pending modal immediately.
  // For human, UI consumes pending and calls back into engine.
  function setPending(state, p) {
    state.pending = p;
  }
  function clearPending(state) {
    state.pending = null;
  }

  // =============================================================
  // 3. ZONES
  // =============================================================
  function battleChars(p) {
    const out = [];
    if (p.battle.front) out.push({ card: p.battle.front, slot: "front" });
    if (p.battle.back) out.push({ card: p.battle.back, slot: "back" });
    p.battle.wing.forEach((c, i) => {
      if (c) out.push({ card: c, slot: "wing" + (i + 1) });
    });
    return out;
  }

  // All positions on the field, with whether empty (破綻) or occupied.
  // Order matches attack order: front, wing1, wing2, back.
  function battleSlots(p) {
    return [
      { slot: "front", card: p.battle.front },
      { slot: "wing1", card: p.battle.wing[0] },
      { slot: "wing2", card: p.battle.wing[1] },
      { slot: "back",  card: p.battle.back },
    ];
  }

  function isInBattle(p, card) {
    if (!card) return null;
    if (p.battle.front === card) return "front";
    if (p.battle.back === card) return "back";
    const wi = p.battle.wing.indexOf(card);
    if (wi >= 0) return "wing" + (wi + 1);
    return null;
  }

  // Returns Lv a card occupies on field (default card.level).
  // Some cards have AUTO Lv-modifiers — we apply `_lvMod` if set
  // by those effects (real implementation is partial).
  function cardEffectiveLv(card) {
    if (!card) return 0;
    return card.level + (card._lvMod || 0);
  }

  function cardEffectivePower(state, side, card) {
    if (!card) return 0;
    let base = DATA.numPower(card.power);
    // Attached cards can add Power (BP01-023 AUTO【FIELD】+1000)
    const att = state.players[side].attached[card._uid] || [];
    for (const a of att) {
      base += attachBonusPower(a, card);
    }
    if (card._powerMod) base += card._powerMod;
    return base;
  }

  function cardEffectiveRange(card) {
    if (!card) return 0;
    return DATA.numRange(card.attackRange) + (card._rMod || 0);
  }

  function attachBonusPower(attCard, host) {
    const t = attCard.effect || "";
    if (t.includes("Power+1000")) return 1000;
    return 0;
  }

  // Compute distance (R) from attacker to target. Per official diagram
  // (page 12): 先鋒↔先鋒 R-1, 側翼 R-2, 後衛 R-3.
  function distance(slotA, slotB) {
    // slot is one of: front, wing1, wing2, back
    const idx = { front: 0, wing1: 1, wing2: 2, back: 3 };
    return Math.abs(idx[slotA] - idx[slotB]);
  }

  // =============================================================
  // 4. BASE 部署 (蓋放 1 張手牌 → 基地, 抽 1 張)
  // =============================================================
  function setDeploy(state, side, handIdx) {
    const p = state.players[side];
    const flags = state.turnFlags[side];
    if (flags.setDeployUsed) return { ok: false, err: "本回合已用過基地部署" };
    if (p.base.faceDown.length >= BASE_SIZE_MAX) {
      return { ok: false, err: `基地已滿（上限 ${BASE_SIZE_MAX}）` };
    }
    const card = p.hand[handIdx];
    if (!card) return { ok: false, err: "手牌索引無效" };
    p.hand.splice(handIdx, 1);
    // Mark as face-down set card (lose effects, not public)
    const set = Object.assign({}, card, { _faceDown: true, _origUid: card._uid });
    set._uid = uid();
    p.base.faceDown.push(set);
    flags.setDeployUsed = true;

    log(state, `${p.name} 基地部署 ${shortName(card)}（蓋卡）→ 抽 1`, side);
    drawN(state, side, 1);
    return { ok: true };
  }

  // =============================================================
  // 5. 行動號召 (CALL)
  // =============================================================
  // 官方規則：Lv ≤ 3 直接放場上；Lv ≥ 4 要 retreat 我方場上 ≥1 張，
  // 合計 Lv = 該角色 Lv。每回合最多 3 次（先攻首回合 1 次）。
  // 蓋卡可作 Lv 1 用作 retreat cost。
  function callCard(state, side, handIdx, retreatUids) {
    const p = state.players[side];
    const flags = state.turnFlags[side];
    if (flags.callCount >= maxCallCount(state, side)) {
      return { ok: false, err: `行動號召次數已用完（${maxCallCount(state, side)} 次/回合）` };
    }
    const card = p.hand[handIdx];
    if (!card) return { ok: false, err: "手牌索引無效" };

    // 默認進 front；如果已有 front，必須先空置 — 戰基移動用唔係 call
    // 官方 call 流程：放進場上空置戰區，UI 處理（基於哪格空放落去）。
    // 我哋簡化：call 後面放 FRONT。Lv 4+ 可退蓋卡充 Lv 1。
    const lv = cardEffectiveLv(card);

    if (lv >= 4) {
      const sources = [];
      let sumLv = 0;
      for (const uidStr of (retreatUids || [])) {
        // find in battle or base
        const c = findAnywhereOnField(p, uidStr);
        if (!c) continue;
        // 蓋卡當 Lv1
        const cLv = c._faceDown ? 1 : cardEffectiveLv(c);
        sumLv += cLv;
        sources.push(c);
      }
      if (sumLv !== lv) {
        return { ok: false, err: `號召 Lv${lv} 需要 retreat 合計 Lv = ${lv}（目前 ${sumLv}）` };
      }
      sources.forEach(c => retreatCard(state, side, c, "號召 cost"));
    }

    // 放進場上空置戰區 — 官方規則：號召可放進任何空置戰區
    // （先鋒/側翼×2/後衛）。BUGFIX：front 已佔時唔可以覆蓋，
    // 要自動搵下一個空置戰區，全部滿就 error。
    p.hand.splice(handIdx, 1);
    const slot = firstEmptyBattleSlot(p);
    if (!slot) {
      // rollback: 冇空位就唔可以號召（手牌還原）
      p.hand.splice(handIdx, 0, card);
      return { ok: false, err: "戰區已滿（先鋒/側翼×2/後衛都有人）" };
    }
    p.battle[slot] = card;
    if (slot === "wing1") p.battle.wing[0] = card;
    else if (slot === "wing2") p.battle.wing[1] = card;
    flags.callCount += 1;
    p._placedThisTurn = p._placedThisTurn || {};
    p._placedThisTurn[card._uid] = true;   // 戰基移動限制
    log(state, `${p.name} 號召 ${shortName(card)} → ${slotLabel(slot)}（Lv${lv}）`, side);
    // M1: descriptor 路徑 — 優先行 effects interpreter，fallback 舊 regex
    if (Array.isArray(card.effects) && card.effects.length) {
      log(state, `[DSL] ${shortName(card)} descriptor 觸發（${card.effects.length} blocks）`, side);
      global.MHR_EFFECTS.runEffects(state, side, {
        kind: "enter_field",
        source: card,
        byCalling: true,
        retreatCount: (retreatUids || []).length,
      });
    } else {
      triggerEnter(state, side, card);
    }
    return { ok: true };
  }

  function firstEmptyBattleSlot(p) {
    if (!p.battle.front) return "front";
    if (!p.battle.wing[0]) return "wing1";
    if (!p.battle.wing[1]) return "wing2";
    if (!p.battle.back) return "back";
    return null;
  }

  function findAnywhereOnField(p, uidStr) {
    if (p.battle.front && p.battle.front._uid === uidStr) return p.battle.front;
    if (p.battle.back && p.battle.back._uid === uidStr) return p.battle.back;
    for (const w of p.battle.wing) {
      if (w && w._uid === uidStr) return w;
    }
    for (const c of p.base.faceDown) {
      if (c && c._uid === uidStr) return c;
    }
    return null;
  }

  function findCardOnField(p, uid) {
    // Same as findAnywhereOnField
    return findAnywhereOnField(p, uid);
  }

  function retreatCard(state, side, card, reason) {
    const p = state.players[side];
    if (p.battle.front === card) p.battle.front = null;
    else if (p.battle.back === card) p.battle.back = null;
    else {
      const wi = p.battle.wing.indexOf(card);
      if (wi >= 0) p.battle.wing[wi] = null;
    }
    // also remove from base if face-down
    const bi = p.base.faceDown.indexOf(card);
    if (bi >= 0) p.base.faceDown.splice(bi, 1);

    const att = p.attached[card._uid] || [];
    delete p.attached[card._uid];
    p.retreat.push(card, ...att);
    log(state, `${p.name} ${shortName(card)} → RETREAT（${reason || "retreat"}）`, side);
  }

  // =============================================================
  // 6. 戰基移動 (戰區 ↔ 基地)
  // =============================================================
  // 規則：每場上角色每回合 1 次戰基移動；當回合放置進場嘅角色不能移動。
  function battleBaseMove(state, side, uid, toBase) {
    const p = state.players[side];
    const flags = state.turnFlags[side];
    const c = findAnywhereOnField(p, uid);
    if (!c) return { ok: false, err: "場上搵唔到該卡" };
    const slot = isInBattle(p, c);
    if (p._placedThisTurn && p._placedThisTurn[uid]) {
      return { ok: false, err: "當回合放置進場嘅角色不能戰基移動" };
    }
    if (flags.movedUids[uid]) return { ok: false, err: "該角色本回合已用過戰基移動" };

    if (toBase) {
      if (p.base.faceDown.length >= BASE_SIZE_MAX) return { ok: false, err: `基地已滿` };
      if (!slot) return { ok: false, err: "該卡唔喺戰區" };
      // 移去基地（becomes 蓋卡 - loses effect, not public）
      if (p.battle.front === c) p.battle.front = null;
      else if (p.battle.back === c) p.battle.back = null;
      else {
        const wi = p.battle.wing.indexOf(c);
        if (wi >= 0) p.battle.wing[wi] = null;
      }
      const set = Object.assign({}, c, { _faceDown: true });
      set._uid = uid;       // keep uid so movedUids still works
      p.base.faceDown.push(set);
      flags.movedUids[uid] = true;
      log(state, `${p.name} ${shortName(c)} 戰基移動：${slotLabel(slot)} → 基地（蓋卡）`, side);
    } else {
      if (p.battle.front) return { ok: false, err: "先鋒已有人，無法搬入戰區" };
      // base → battle: take first face-down that matches this uid
      const bi = p.base.faceDown.indexOf(c);
      if (bi < 0) return { ok: false, err: "該卡唔喺基地" };
      p.base.faceDown.splice(bi, 1);
      const faceUp = Object.assign({}, c);
      faceUp._faceDown = false;
      p.battle.front = faceUp;
      flags.movedUids[uid] = true;
      log(state, `${p.name} ${shortName(c)} 戰基移動：基地 → 先鋒（翻面）`, side);
    }
    return { ok: true };
  }

  function slotLabel(slot) {
    return { front: "先鋒", back: "後衛", wing1: "側翼-1", wing2: "側翼-2" }[slot] || slot;
  }

  // =============================================================
  // 7. BATTLE PHASE
  // =============================================================
  // 順序：先鋒 → 側翼(2 格可自定先後) → 後衛
  // 攻擊：選 R 值內敵方角色或破綻作目標
  // 結算：角色vs角色 (大勝/小敗/相殺)，角色vs破綻 (+1 RP)
  function attackableTargets(state, attackerSide, attackerUid) {
    const atkP = state.players[attackerSide];
    const defP = state.players[attackerSide === "P" ? "A" : "P"];
    const atk = findAnywhereOnField(atkP, attackerUid);
    if (!atk) return [];
    const aSlot = isInBattle(atkP, atk);
    if (!aSlot) return [];
    const range = cardEffectiveRange(atk);
    const targets = [];
    for (const t of battleSlots(defP)) {
      if (distance(aSlot, t.slot) <= range) {
        if (t.card) {
          // 攔截 keyword: if defender has 攔截, redirect to them
          if (hasAbility(t.card, "攔截")) {
            // already the target
          }
          targets.push({ kind: "card", slot: t.slot, card: t.card, dist: distance(aSlot, t.slot) });
        } else {
          // 破綻
          targets.push({ kind: "weakness", slot: t.slot, dist: distance(aSlot, t.slot) });
        }
      }
    }
    return targets;
  }

  // Execute an attack. target may be:
  //   { kind: "card", slot, card }
  //   { kind: "weakness", slot }
  // v3.9.1: 守方係人類（P）時，應對步驟會 pause 等 UI 揀 COUNTER →
  //         resolveCounter(state, decision) 續行（AI 守方照舊自動）
  function attack(state, attackerSide, attackerUid, target) {
    const atkP = state.players[attackerSide];
    const flags = state.turnFlags[attackerSide];
    const atk = findAnywhereOnField(atkP, attackerUid);
    if (!atk) return { ok: false, err: "攻擊者唔喺場上" };
    if (flags.attackedUids[attackerUid]) {
      if (!flags.doubleAttackUids[attackerUid]) {
        return { ok: false, err: "本角色本回合已攻擊過" };
      }
    }

    // Set attacked flag
    flags.attackedUids[attackerUid] = true;

    // ②應對步驟：守方 COUNTER（M4：DSL 優先，舊 regex fallback 跳過 descriptor 卡）
    const defSide = attackerSide === "P" ? "A" : "P";
    const humanDef = !!state.pendingHuman && defSide === "P";
    if (humanDef) {
      // 真人守方：有 COUNTER 揀 → pause 等 UI（resolveCounter）；冇就直接結算
      const opts = collectCounterOptions(state, defSide, attackerUid);
      if (opts.length) {
        setPending(state, {
          kind: "counter",
          attackerSide, attackerUid, target, defSide, opts,
          title: "AI 攻擊你 — 應對步驟（COUNTER）",
        });
        return { ok: true, paused: "counter" };
      }
    } else {
      if (global.MHR_EFFECTS && global.MHR_EFFECTS.runEffects) {
        global.MHR_EFFECTS.runEffects(state, defSide, { kind: "counter", attackerUid });
      }
      useCounter(state, defSide, attackerUid);
    }
    return finishAttack(state, attackerSide, attackerUid, target);
  }

  // v3.9.1: 真人守方應對決策 — resolveCounter(state, { use: true, idx }) / { use: false }
  function resolveCounter(state, decision) {
    const pend = state.pending;
    if (!pend || pend.kind !== "counter") return { ok: false, err: "冇 pending counter 決策" };
    const defP = state.players[pend.defSide];
    if (decision && decision.use) {
      const opt = (pend.opts || []).find(o => o.idx === decision.idx);
      if (!opt) return { ok: false, err: "選擇無效" };
      const card = defP.hand[opt.idx];
      if (!card) return { ok: false, err: "手牌冇呢張卡" };
      defP.hand.splice(opt.idx, 1);
      defP.retreat.push(card);
      const atk = findAnywhereOnField(state.players[pend.attackerSide], pend.attackerUid);
      if (atk) {
        atk._powerMod = (atk._powerMod || 0) - opt.power;
        log(state, `[COUNTER] ${defP.name} 用 ${shortName(card)} 應對：${shortName(atk)} -${opt.power} Power（本回合）`, pend.defSide);
      }
    } else {
      log(state, `${defP.name} 唔用 COUNTER 應對`, pend.defSide);
    }
    clearPending(state);
    return finishAttack(state, pend.attackerSide, pend.attackerUid, pend.target);
  }

  // 守方可揀嘅 COUNTER 手牌（已實裝子集 = 引擎 useCounter 同一子集：COUNTER·ACTI【HAND】+ Power-N）
  function collectCounterOptions(state, defSide, attackerUid) {
    const p = state.players[defSide];
    const out = [];
    p.hand.forEach((c, i) => {
      if (!c || !c.effect) return;
      if (Array.isArray(c.effects) && c.effects.length) return;   // DSL 卡由 interpreter 處理（暫未支援 prompt）
      if (!/COUNTER·ACTI/i.test(c.effect)) return;
      const m = c.effect.match(/Power-(\d+)/);
      if (!m) return;
      out.push({ idx: i, power: parseInt(m[1], 10), name: shortName(c), card: c });
    });
    return out;
  }

  // 應對步驟之後嘅攻擊結算（weakness / 角色對戰），attack 同 resolveCounter 共用
  function finishAttack(state, attackerSide, attackerUid, target) {
    const atkP = state.players[attackerSide];
    const defP = state.players[attackerSide === "P" ? "A" : "P"];
    const atk = findAnywhereOnField(atkP, attackerUid);
    if (!atk) return { ok: false, err: "攻擊者唔喺場上" };

    if (target.kind === "weakness") {
      const aPower = cardEffectivePower(state, attackerSide, atk);
      log(state, `${atkP.name} ${shortName(atk)} (P${aPower}) 攻擊 ${slotLabel(target.slot)}破綻`, attackerSide);
      gainRushPoint(state, attackerSide, `攻破綻 ${slotLabel(target.slot)}`);
      return { ok: true, result: "weakness" };
    }

    const tgt = target.card;
    const aPower = cardEffectivePower(state, attackerSide, atk);
    const tPower = cardEffectivePower(state, attackerSide === "P" ? "A" : "P", tgt);
    log(state, `${atkP.name} ${shortName(atk)} (P${aPower}) 攻 ${defP.name} ${shortName(tgt)} (P${tPower})`, attackerSide);

    let atkRetreat = false, tgtRetreat = false;
    if (aPower > tPower) tgtRetreat = true;
    else if (aPower < tPower) atkRetreat = true;
    else { atkRetreat = true; tgtRetreat = true; }

    if (tgtRetreat) {
      retreatCard(state, attackerSide === "P" ? "A" : "P", tgt, "戰敗");
    }
    if (atkRetreat) {
      retreatCard(state, attackerSide, atk, "戰敗");
    }
    if (aPower > tPower && hasAbility(atk, "強襲")) {
      gainRushPoint(state, attackerSide, "強襲（攻擊戰勝）");
    }
    return { ok: true, result: atkRetreat ? (tgtRetreat ? "both" : "attacker_lost") : (tgtRetreat ? "attacker_won" : "draw?") };
  }

  function isPaused(state) {
    return !!state.pending;
  }

  // Helper: check if a card has a 能力 keyword
  function hasAbility(card, kw) {
    if (!card) return false;
    const t = card.effect || "";
    return t.indexOf(kw) >= 0;
  }

  // =============================================================
  // 8. RUSH POINT / WIN
  // =============================================================
  function gainRushPoint(state, side, why) {
    const p = state.players[side];
    if (p.timeline.length >= RUSH_TO_WIN) return;
    p.timeline.push(p.rushDeck.shift());
    p.rushPoints = p.timeline.length;
    log(state, `${p.name} +1 Rush Point（${why}）→ 時間線 ${p.timeline.length}/${RUSH_TO_WIN}`, side);
    checkWin(state);
  }

  function checkWin(state) {
    if (state.winner) return;
    if (state.players.P.timeline.length >= RUSH_TO_WIN) {
      state.winner = "P";
      log(state, `時間線滿 9 張，Player 獲勝！`);
    } else if (state.players.A.timeline.length >= RUSH_TO_WIN) {
      state.winner = "A";
      log(state, `時間線滿 9 張，AI 獲勝！`);
    }
  }

  // =============================================================
  // 9. EFFECT IMPLEMENTATIONS (partial — see README v0.2)
  // =============================================================
  // Priority order: TRIG【FIELD】on enter, AUTO continuous refresh,
  // COUNTER·ACTI from HAND, ONCE PER TURN. Most still stub.

  function triggerEnter(state, side, card) {
    const t = card.effect || "";
    if (!t.trim()) {
      log(state, `[效果未實裝] ${shortName(card)} 入場`, side);
      return;
    }
    // Pattern: "you draw 1 card" / "you draw N cards"
    const drawMatch = t.match(/you draw (\d+) cards?/i);
    if (drawMatch) {
      const n = parseInt(drawMatch[1], 10);
      drawN(state, side, n);
      log(state, `[效果] ${shortName(card)} 入場：抽 ${n}`, side);
      if (/second chance to attack/i.test(t)) {
        state.turnFlags[side].doubleAttackUids[card._uid] = true;
        log(state, `[效果] ${shortName(card)} 本回合可攻擊 2 次`, side);
      }
      return;
    }
    // Pattern: "you prune 1 of your opponent's characters"
    if (/you prune 1 of your opponent's character/i.test(t)) {
      const opp = side === "P" ? "A" : "P";
      const oppBattle = battleChars(state.players[opp]);
      const lvMatch = t.match(/Lv(\d+) or below/i);
      const maxLv = lvMatch ? parseInt(lvMatch[1], 10) : 99;
      const powMatch = t.match(/Power (\d+) or lower/i);
      const maxPow = powMatch ? parseInt(powMatch[1], 10) : 99999;
      const tgt = oppBattle.find(x => cardEffectiveLv(x.card) <= maxLv && cardEffectivePower(state, opp, x.card) <= maxPow);
      if (tgt) {
        pruneCard(state, opp, tgt.card);
        log(state, `[效果] ${shortName(card)} 入場：除外 ${shortName(tgt.card)}`, side);
      } else {
        log(state, `[效果] ${shortName(card)} 入場：無合法目標除外`, side);
      }
      return;
    }
    // Pattern: opponent's character in FRONT gets Power-X000
    if (/opponent's character in FRONT gets Power-/i.test(t)) {
      const opp = side === "P" ? "A" : "P";
      const target = state.players[opp].battle.front;
      if (target) {
        const m = t.match(/Power-(\d+)/);
        const amt = m ? parseInt(m[1], 10) : 0;
        target._powerMod = (target._powerMod || 0) - amt;
        log(state, `[效果] ${shortName(card)}：${shortName(target)} -${amt} Power`, side);
      }
      return;
    }
    // Pattern: face down into BASE
    if (/place .* face down into your BASE/i.test(t)) {
      const m = t.match(/place the top (\d+) cards? of your deck face down/i);
      const n = m ? parseInt(m[1], 10) : 1;
      for (let i = 0; i < n; i++) {
        if (state.players[side].deck.length === 0) break;
        const c = state.players[side].deck.shift();
        const set = Object.assign({}, cloneCard(c), { _faceDown: true });
        state.players[side].base.faceDown.push(set);
      }
      log(state, `[效果] ${shortName(card)} 入場：${n} 張蓋放 BASE`, side);
      return;
    }
    // fall-through
    log(state, `[效果未實裝] ${shortName(card)}：${truncate(t, 50)}`, side);
  }

  function pruneCard(state, side, card) {
    const p = state.players[side];
    if (p.battle.front === card) p.battle.front = null;
    else if (p.battle.back === card) p.battle.back = null;
    else {
      const wi = p.battle.wing.indexOf(card);
      if (wi >= 0) p.battle.wing[wi] = null;
    }
    const att = p.attached[card._uid] || [];
    delete p.attached[card._uid];
    p.voidZone.push(card, ...att);
    log(state, `${p.name} ${shortName(card)} → VOID（裁剪）`, side);
  }

  // COUNTER·ACTI: discard from HAND to apply Power-N to attacker
  // M4: descriptor 卡（Array.isArray(c.effects)）由 DSL interpreter 處理，呢度跳過
  function useCounter(state, defenderSide, attackerUid) {
    const p = state.players[defenderSide];
    for (let i = 0; i < p.hand.length; i++) {
      const c = p.hand[i];
      if (!c.effect) continue;
      if (Array.isArray(c.effects) && c.effects.length) continue; // DSL 路徑
      if (!/COUNTER·ACTI/i.test(c.effect)) continue;
      const m = c.effect.match(/Power-(\d+)/);
      if (!m) continue;
      const amt = parseInt(m[1], 10);
      p.hand.splice(i, 1);
      p.retreat.push(c);
      const atkP = state.players[defenderSide === "P" ? "A" : "P"];
      const atk = findAnywhereOnField(atkP, attackerUid);
      if (atk) {
        atk._powerMod = (atk._powerMod || 0) - amt;
        log(state, `[COUNTER] ${p.name} 棄 ${shortName(c)}：${shortName(atk)} -${amt} Power`, defenderSide);
      }
      return true;
    }
    return false;
  }

  // =============================================================
  // 10. UTILITIES
  // =============================================================
  function shortName(c) {
    if (!c) return "?";
    return (c.name || "").replace(/^「.*」/, "").trim() || c.name;
  }
  function truncate(s, n) {
    if (!s) return "";
    return s.length > n ? s.slice(0, n) + "…" : s;
  }

  // =============================================================
  // PUBLIC API
  // =============================================================
  global.MHR_ENGINE = {
    initGame,
    mulligan,
    injectEffects,   // M4: 測試/工具用 — 手動將 descriptor 注入卡實例
    startTurn,
    endTurn,
    setDeploy,
    callCard,
    battleBaseMove,
    retreatCard,
    attack,
    resolveCounter,
    collectCounterOptions,
    isPaused,
    attackableTargets,
    useCounter,
    cardEffectivePower,
    cardEffectiveRange,
    cardEffectiveLv,
    battleChars,
    battleSlots,
    findCardOnField,
    findAnywhereOnField,
    isInBattle,
    shortName,
    drawTo,
    drawN,
    discardDownTo,
    gainRushPoint,
    checkWin,
    hasAbility,
    distance,
    setPending,
    clearPending,
    maxCallCount,
    isFirstTurnBattleSkipped,
    EVT,
    RUSH_TO_WIN,
    HAND_SIZE_START,
    HAND_SIZE_MAX,
    BASE_SIZE_MAX,
    RUSH_DECK_SIZE,
  };
})(window);
